# Generated by Django 5.1.2 on 2024-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_catalogo',
            fields=[
                ('id_catalogo', models.AutoField(db_column='id_catalogo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=500, null=True, verbose_name='Descripción')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creación')),
            ],
            options={
                'verbose_name': 'catálogo',
                'verbose_name_plural': 'catálogos',
                'db_table': 'catálogo',
                'ordering': ['nombre'],
            },
        ),
    ]
